FROM ubuntu

# WORKDIR

#Update apt
RUN apt-get update

#install wget and unzip
RUN apt-get install -y \
    wget \
    unzip \
    git \
    tmux \
    vim 
# && rm -rf /var/lib/apt/lists/*

#Move into root directory
WORKDIR /root

RUN git clone https://github.com/Ronster2018/Local-IDE-config.git 

RUN chmod 766 Local-IDE-config/ide.sh

#Install Terraform
RUN wget --quiet https://releases.hashicorp.com/terraform/0.14.6/terraform_0.14.6_linux_amd64.zip \
    && unzip terraform_0.14.6_linux_amd64.zip \
    && mv terraform /usr/bin \
    && rm terraform_0.14.6_linux_amd64.zip

# Create symlinks
RUN ln -snf Local-IDE-config/.tmux.conf ~/.tmux.conf
RUN ln -snf Local-IDE-config/.vimrc ~/.vimrc
RUN mkdir ~/.vim/undodir -p

#Check that Terraform is installed
RUN terraform --version

CMD [ "tmux" ]