vote:
  image: schoolofdevops/vote
  links:
    - redis:redis
  ports:
    - 5000:80
    networks:
    - front-tier
    - back-tier

redis:
  image: redis:alpine

worker:
  image: schoolofdevops/vote-worker
  links:
    - redis:redis 
  networks:
    - back-tier

db:
  image: postgres
  container_name: db
  volumes:
    - "db-data:/var/lib/postgresql/data"
    networks:
    - back-tier

networks:
  front-tier
  back-tier