version: '3.8'
services:
  terraform:
    build: .
    volumes:
      - type: bind
        source: ./Volumes
        target: /root/volume
    # entrypoint: ['tmux']
    stdin_open: true # docker run -i
    tty: true # docker run -t
